# ******************************************************************************
#  Copyright (c) 2021 Nurul-GC.                                                *
# ******************************************************************************

# Generated by Django 3.2.7 on 2021-09-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(upload_to='logos/%Y/')),
                ('language', models.CharField(choices=[('English', 'English'), ('Português', 'Português')], help_text='Escolha o idioma do certificado!', max_length=10)),
                ('document_title', models.CharField(help_text='Digite um titulo para o documento!', max_length=50)),
                ('document_subject', models.CharField(choices=[('Certificado de Participação', 'Certificado de Participação'), ('Certificate of Participation', 'Certificate of Participation')], help_text='Escolha o tema do certificado!', max_length=30)),
                ('company_name', models.CharField(help_text='Digite o nome da instituição emissora!', max_length=50)),
                ('student_name', models.CharField(help_text='Digite o nome do estudante!', max_length=50)),
                ('description', models.TextField(help_text='Digite o conteudo descritivo e motivo desta certificação!', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(upload_to='logos/%Y/')),
                ('language', models.CharField(choices=[('English', 'English'), ('Português', 'Português')], help_text='Escolha o idioma do certificado!', max_length=10)),
                ('document_title', models.CharField(help_text='Digite um titulo para o documento!', max_length=50)),
                ('document_subject', models.CharField(choices=[('Training Certificate', 'Training Certificate'), ('Certificado de Formação', 'Certificado de Formação')], help_text='Escolha o tema do certificado!', max_length=30)),
                ('company_name', models.CharField(help_text='Digite o nome da instituição emissora!', max_length=50)),
                ('student_name', models.CharField(help_text='Digite o nome do estudante!', max_length=50)),
                ('course_name', models.CharField(help_text='Digite o nome do curso!', max_length=50)),
                ('description', models.TextField(help_text='Digite o conteudo descritivo e motivo desta certificação!', max_length=1000)),
            ],
        ),
    ]
